
version: 2

sources:
    -   name: dbtx
        database: dbtx2
        schema: public
       
        tables: 
            -   name: customers
            -   name: products
            -   name: orders
            